### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-sky#12]
Before Gamma 2016 we should add a section where we give credit to people and projects that have helped create gamma-sky.

Here's the start of an incomplete list:
- MPIK for giving us time to work on this
- Github and gh-pages for serving our app for free.
- People:
  - Thomas from Aladin Lite
- Data sources:
  - Fermi-LAT for the data / tools
  - Planck
  - SNRCat
    Tools:
  - http://aladin.u-strasbg.fr/aladin.gml#Acknowledgement
  - https://angular.io/
  - http://www.astropy.org/ and http://gammapy.org/

I'm not sure where this fits on the webpage.
Maybe we can just have a Markdown file in the repo and link to it from the webpage?

**Comment by vorugantia** [comment]
See [here](https://github.com/gammapy/gamma-sky/wiki/Datasets) and [here](https://github.com/gammapy/gamma-sky/wiki/Overview#acknowledgements).
