### ISSUE TITLE
How to handle overlapping sources?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-sky#13]
There's a few sources where we have multiple catalog entries.
E.g. the Crab has two 3FGL and one 2FHL entry that's almost at the same position.

One has to zoom in very far to see that there's multiple markers:

![screen shot 2016-07-01 at 10 37 21](https://cloud.githubusercontent.com/assets/852409/16516338/d8385136-3f77-11e6-8862-d0f3b466c4d6.png)

I'm not sure how to make this better ... I know that I've seen a d3 package that separates the points a little automatically when one hovers over them. Probably not easy to implement.

This is low priority, just a reminder issue.

**Comment by vorugantia** [comment]
See the first Aladin Lite "issue" [here](https://github.com/gammapy/gamma-sky/wiki/Aladin-Lite-issues-and-feature-requests#issues). If we get access to control the order of markers to be displayed, then our problem will be solved.
