### ISSUE TITLE
Add "version" and "last modified" to the "About" popup

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-sky#16]
I think we should have a version number (e.g. "version 0.1") and last modified date stamp (e.g. "July 7, 2016") in the "About" popup on the webpage.

This will be useful for us to see which version is deployed, but also for users.

A nice way to implement it is to store those pieces of info in a separate hand-written file `gamma-sky.info.json`.
That way it's under version control, and accessible both from Python and JS scripts.
(Although for now we'll just access it from JS to display on the webpage)

**Comment by vorugantia** [comment]
Version number was added in 2ccb2dde6c291e1f95157a280aef4ce4c6701e77.

Last modified date was added in d70db03c8790340e1d01ae1f2e2771cca958b2e3.

**Comment by cdeil** [comment]
Thanks!
Can you include the version number increase in the checklist for deploy at the appropriate place (probably towards the start or the steps)?
