### ISSUE TITLE
Configure base image layer options

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-sky#18]
Currently we have the following available images for the "base image layer":

![screen shot 2016-07-07 at 20 52 11](https://cloud.githubusercontent.com/assets/852409/16665670/bd06bd1e-4484-11e6-9f60-42b491c5acf7.png)

These aren't the most interesting images to compare with the gamma-ray sky.
We should configure it to something better, more like http://www.chromoscope.net/

It looks like that list is defined here in the `HpxImageSurvey.SURVEYS` array:
https://github.com/gammapy/gamma-sky/blob/gh-pages/static/aladin.js#L8065

@vorugantia - Could you try modifying it? E.g. maybe it's possible to modify that array before calling the Aladin widget constructor?

A list of available HIPS images at CDS is available here:
http://aladin.u-strasbg.fr/hips/list

We want e.g. one from INTEGRAL:
- http://alasky.u-strasbg.fr/INTGAL/INTColor/
- http://skies.esac.esa.int/Integral/color/

But let's separate the discussion of which images to show from the question how to implement that selection, i.e. do the discussion elsewhere / later.

**Comment by vorugantia** [comment]
This issue is old and we've figured out how to show only certain maps. But we haven't added any images from INTEGRAL yet, as you mentioned above. Should we still add one, or both of them?

**Comment by cdeil** [comment]
+1 to add one or both INTEGRAL maps.

@registerrier - Which one would you recommend?
- http://alasky.u-strasbg.fr/INTGAL/INTColor/
- http://skies.esac.esa.int/Integral/color/

**Comment by registerrier** [comment]
The second one looks better (less secondary features, more sky coverage, more recent). 
You also have the maps in the 3 energy bands available
- http://skies.esac.esa.int/Integral/20-35/
- http://skies.esac.esa.int/Integral/35-65/
- http://skies.esac.esa.int/Integral/65-100/

**Comment by cdeil** [comment]
@vorugantia - Can you add the second one.

You could also mention the extra ones @registerrier mentioned here:
https://github.com/gammapy/gamma-sky/wiki/Datasets#images
and make an issue that eventually the image selection should be changed so that loading an arbitrary HIPS image from http://aladin.u-strasbg.fr/hips/list should be possible, i.e. the Aladin Lite base image widget should be wrapped or extended.

Maybe this is a feature we could email Thomas about now?

**Comment by vorugantia** [comment]
Added the second Integral map in 31717f3e3c7bbd2ebebf8b7f3d027b1f9b199ecf. I'll also open the new issue.
