### ISSUE TITLE
Set up Google analytics?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-sky#26]
Maybe we should set up Google analytics to track how much the page is used?
https://analytics.google.com/

I don't know if there are any drawbacks or concerns.

**Comment by cdeil** [comment]
@vorugantia - Could you please look into this task? Maybe read a bit about how it works, or even try it out for some dummy separate page you put on Github pages?

I think it's very important to have at least the basic information on how many visitors gamma-sky.net has, i.e. whether anyone is using it.

**Comment by vorugantia** [comment]
This has been done - link can be found in the Wiki under the `Developer documentation` tab.
