### ISSUE TITLE
Improvement for http://gamma-sky.net/

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-sky#3]
@vorugantia - I suggest the following changes to http://gamma-sky.net/
- For me, the canvas doesn't fill the browser window exactly. There's some small space on the top and left that's unused, and some of the canvas at the right and bottom is cut off in Chrome. Do you see the same? Can you try to fix it?
- Change default image to Fermi color
- Change default coordinate system from ICRS to Galactic
- Default position = Galactic center
- Load full Fermi 3FGL catalog

**Comment by cdeil** [comment]
Also -- change color map to inverse rainbow. 

(Just kidding ... please don't!)
:-)

**Comment by vorugantia** [comment]
Done
