### ISSUE TITLE
Implement some tests

### ISSUE THREAD

**Issue by vorugantia** [gammapy/gamma-sky#34]
Right now, the spec.ts files generated by angular-cli's `ng generate` are not running any useful tests. We want to implement unit tests on each component's and service's specific variables, routes, etc.

See these guides:
- http://chariotsolutions.com/blog/post/testing-angular-2-components-unit-tests-testcomponentbuilder/
- https://medium.com/google-developer-experts/angular-2-unit-testing-with-jasmine-defe20421584#.e7xsffpxf
- https://angular.io/docs/ts/latest/guide/testing.html (not completed yet)

**Comment by cdeil** [comment]
We will not have time to figure out how to test an Angular app well and implement tests.

If possible, we should try to find the time to add a few very high-level tests
Navigate to a given URL and check that some content is on the webpage.

E.g. navigate to `/cat/2fhl/2` and check that `Source Name: 2FHL J0018.5+2947` is on the page.
@vorugantia - Do you know how to add such a test? Can you try to add this one example?

**Comment by vorugantia** [comment]
High-level tests have been implemented in #77 and #79. These are `e2e` tests that route to a certain page and check for content, etc. Later on we can add unit tests, but I see that as lesser priority until we get all of the content on the webpage.

Closing this issue...
