### ISSUE TITLE
CSS styles

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-sky#36]
Concerning yesterday’s discussion how to avoid duplication of css style code.

There’s a very simple solution … every component can have a list of styles from multiple css files applied by listing those files in `styleUrls`:

https://angular.io/docs/ts/latest/guide/component-styles.html#!#loading-styles

So every time we have shared styles, we can just add those in `css` files that are then applied to multiple components.
E.g. we could start with one such global style that defines the fonts and gets applied to all components that show text.

Probably we should use a CSS framework to get nice styling with little work.
I'm only familiar with bootstrap, so that would be my preference.
I've never used it in combination with Angular 2 though.

Looks like this is the most popular option:
https://github.com/valor-software/ng2-bootstrap

And this one is also popular:
https://github.com/ng-bootstrap/ng-bootstrap

There's also material design:
https://github.com/angular/material2
but it's very early in development, I'm not sure if it would work for us yet.

In any case: let's talk about styling next week, let's first get the app functional.

**Comment by vorugantia** [comment]
In fact, `ng2-select` (which I'm looking into now) already uses `ng2-bootsteap` as a dependency, so perhaps it is the way to go for us. But I agree, we can figure out styling later.

**Comment by cdeil** [comment]
👍  to pull in `ng2-bootstrap` and `ng2-select` now and get a minimal working, styled select box implemented.
