### ISSUE TITLE
Map share URL

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-sky#49]
@vorugantia - I'm using the JS console at
http://aladin.u-strasbg.fr/AladinLite/doc/API/examples/AL-init-custom-options/
to play around with Aladin Lite a bit.

One method I noticed was this:

```
> aladin.getShareURL()
< "http://aladin.u-strasbg.fr/AladinLite/?target=06%2009%2039.000%2B20%2029%2012.12&fov=1.50&survey=P%2FallWISE%2Fcolor"
```

I'm not sure if / how we can use this for our app yet.
Maybe, as long as it's not connected to the router and app state, it could be exposed via a "share" button?

**Comment by vorugantia** [comment]
I noticed it too today, forgot to tell you, but it would definitely be good to see if we can make use of it.

**Comment by cdeil** [comment]
I'm not sure we can use it directly, if we want to keep control of the URL and use it for our router though. To be investigated ...

**Comment by vorugantia** [comment]
Done.
