### ISSUE TITLE
Bug when clicking on SNRcat source

### ISSUE THREAD

**Issue by vorugantia** [gammapy/gamma-sky#53]
Every time I click on an SNRcat source in MapView, all of the text in the toolbox and the about button text gets aligned to the right. See before and after pics below. 

![snrcat_bug2](https://cloud.githubusercontent.com/assets/18579919/17822782/ef40dd50-6626-11e6-8903-d6a49a859a0d.PNG)

![snrcat_bug](https://cloud.githubusercontent.com/assets/18579919/17822781/e8e6f476-6626-11e6-922a-4fd89787e8a0.PNG)

It's probably an easy fix and I'll just do it later. This is just a reminder for myself

**Comment by cdeil** [comment]
Putting 0.2 milestone for now (which is the next release we deploy soon).
@vorugantia - Doesn't sound critical, feel free to move the issue to 0.3 or even later.

**Comment by vorugantia** [comment]
Fixed in commit 8c9d3b113f59d1b6d58bc241745b7045b60f3193. Closing issue...
