### ISSUE TITLE
Update to Angular 2 final

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-sky#54]
Angular 2 final was realeased:
http://angularjs.blogspot.de/2016/09/angular2-final.html

We are currently on `2.0.0-rc.4` and should update.
- A big change was the introduction of `NgModules`, with info how to update here:
  https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html
- Another big change was SystemJS -> webpack

I'm not sure how to best do the update yet.

I guess roughly the options are:
1. use the CLI to make a new project to get a cleanly set up and working project following latest best practices, then copy over existing code piece by piece.
2. make changes to the current app, after reading through the RC4 to RC5 migration guide.

@vorugantia - Any idea which might be better? Will you have time for this in the coming weeks or should I give it a go?

**Comment by vorugantia** [comment]
I should have time in the next few weeks to refactor the code. However, first I want to use my time to finish the paper for the website. Once that has been done, I can get started with updating our code.

I'm also not sure if we should start from scratch or just make changes to our current app...

**Comment by cdeil** [comment]
Closing this old issue now.
@vorugantia did this in #57
