### ISSUE TITLE
Update TeV catalog to gamma-cat

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-sky#58]
We should update the TeV catalog to gamma-cat.

This should be the input file ... I need to add some more info there first:
https://github.com/gammapy/gamma-cat/blob/master/docs/data/gammacat.ecsv

For now I skip the TeV catalog function here:
https://github.com/gammapy/gamma-sky/commit/38344d34e09f129871e29c531146b796e6578e29#diff-076f78bf1d6809bc8d45d25d7565f077R20

I'm assigning this to myself for now, I'll try to find time to do it soon.

**Comment by cdeil** [comment]
By now `gamma-cat` has evolved a bit. I think, at least for now, we should use [gamma-cat/docs/data/gammacat.fits.gz](https://github.com/gammapy/gamma-cat/blob/master/docs/data/gammacat.fits.gz) as input, and dump the info we want to display on gamma-sky.net to a JSON file just like we do for the Fermi-LAT catalogs via the scripts in [gamma-sky/gammasky/catalogs.py](https://github.com/gammapy/gamma-sky/blob/master/gammasky/catalogs.py).

This can be done either directly via `astropy.table.Table`, or with the source catalog and source object classes in `gammapy.catalog`. See [gammapy/catalog/gammacat.py](https://github.com/gammapy/gammapy/blob/master/gammapy/catalog/gammacat.py) and some usage examples in [gammapy/catalog/tests/test_gammacat.py](https://github.com/gammapy/gammapy/blob/master/gammapy/catalog/tests/test_gammacat.py).
In Gammapy we already have code to plot spectral models and spectral points. This is significant work to code up, and for sure this is something we want here (make an SED plot for every Fermi and TeV source), so sooner or later we have to call `gammapy.catalog` from the scripts here anyways.

@vorugantia - Want to take a shot at this?
(start small, just dump source name & position as a start, get that working by commenting out other info in the web code, then we add more info piece by piece)

**Comment by vorugantia** [comment]
Yes, I can get started this week and see where I get.

**Comment by cdeil** [comment]
I'm closing this issue now.

This was done by @vorugantia in #61 and there's #62 still open for further discussion / work.
