### ISSUE TITLE
Which catalog markers to show on page load?

### ISSUE THREAD

**Issue by vorugantia** [gammapy/gamma-sky#59]
Currently, Aladin Lite is showing all catalog markers by default on the map, which is getting a little cluttered:

![capture](https://cloud.githubusercontent.com/assets/18579919/20043081/ab911360-a454-11e6-907d-c6a65dd543ca.PNG)

However, now (thanks to Thomas Boch) I found the workaround to hide certain catalogs on page load (while still keeping the check-box in the toolbar to re-enable them). @cdeil - which catalogs should we hide on page load? I think since 3FGL has the most sources by far, if we were to hide them, the map would look much cleaner on startup.

This is a low priority question, we can decide later.

**Comment by cdeil** [comment]
Maybe only show the image, no catalog at all on page load?

That seems like the cleanest solution, and will also work best as we add more catalogs (HAWC, 4FGL, ...).

I don't feel strongly though, so @vorugantia if you prefer something else, just go ahead and put what you like.

**Comment by vorugantia** [comment]
Maybe we should just show the TeV catalog, since that's the main one we want to feature. We can always change this later.

Implemented in 31717f3e3c7bbd2ebebf8b7f3d027b1f9b199ecf.
