### ISSUE TITLE
Add information to TeV source detail page

### ISSUE THREAD

**Issue by vorugantia** [gammapy/gamma-sky#62]
In our old TeV catalog, we listed all extension, spectral, and distance info for each source's detailed view in `CatViewComponent`. @cdeil formatted the HTML in `cat-source-tev.component.html` and implemented getter methods in `source.ts` to do so.

However, our new TeV catalog organizes its data differently, in columns with new names, and I'm not sure how we would want to present the information in the detailed view. I will need some help doing this.

**Comment by cdeil** [comment]
Basically the info should be sorted by:
- General
- Position
- Morphology
- Spectrum
- References

There's some examples here how to create a link e.g. to TeVCat or (for now) and source input JSON file in gamma-cat: https://gammapy.github.io/gamma-cat/sources.html

And then it would be nice to have extra stuff like an SED plot (where available) or a small Aladin Lite image of the region (e.g. 3 x 3 deg) around the source and a list of nearby sources from the other catalogs.

I think we'll just have to go step by step and add one piece of info and feature at a time, not try to put "all info" on the source detail pages.

@vorugantia  - Do you want to add some more stuff, or should I take a stab at it in the coming days?

**Comment by vorugantia** [comment]
@cdeil - I don't think I can add info for Morphology and Spectrum because there are just too many colnames for e.g. spectral data (starting with "spec") and I'm not sure which info is important/how to display it all. So if you could get that out of the way when you are free, I can go ahead and add SED plots and Aladin Lite images.

**Comment by vorugantia** [comment]
Done.
