### ISSUE TITLE
Catalog data panel

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-sky#8]
It would be nice to have a "data panel" at the side (example: http://sky.esa.int/ has a data panel at the bottom) that displays some catalog data as a table (example: http://gammapy.github.io/web-experiments/?cat=2FHL&source=2) when I click on a given source.

I like the idea of starting with almost 100% of the space for the map, and then to only reduce screen space for the map when the user asks for it, but shrinking the map or painting information or panels on top.

FYI:  I'll just start filing some feature requests for the webpage when I think of something.
Some of them are easy to implement, others a week of work.

As far as I'm concerned, you already have built version 0.1 and it's good enough for now.
So feel free to just pick whatever you find interesting and work on that on hour own time.

**Comment by cdeil** [comment]
Changing milestone to "wishlist".

It's much more important for now to flesh out the catalog source detail views with all available info, and to add the option to link to them from the map popups.

**Comment by vorugantia** [comment]
For now we have a separate view for the detailed data display. Maybe later we will want to change this view to a panel on the map...
